name: CI

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Prettier (check)
        run: npx prettier --check .

      - name: ESLint
        run: npm run lint

      - name: TypeScript (no emit)
        run: npx tsc --noEmit

      - name: If checks failed, suggest local auto-fix
        if: ${{ failure() }}
        run: |
          echo "::group::How to fix locally"
          echo "npm run fix:prettier"
          echo "npm run fix:lint"
          echo "npm run fix:all   # one-shot auto-fix + amend + push"
          echo "::endgroup::"
