name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  lint-typecheck:
    name: Lint & Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npx tsc --noEmit
  npm-audit:
    name: Security Audit (npm)
    runs-on: ubuntu-latest
    needs: lint-typecheck
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm audit --audit-level=high || true

  verify-signed-commits:
    name: Verify Signed Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for unsigned commits
        run: |
          echo "🔍 Checking commit signatures..."
          if git log origin/main..HEAD --pretty='%H %G?' | grep -vE ' G$'; then
            echo "❌ Found unsigned commits. Please sign them with SSH/GPG."
            exit 1
          fi
          echo "✅ All commits are properly signed."
